#pragma once
#include <iostream>
#include <string>
#include <vector>
#include <list>
#include <deque>
#include <iomanip>
#include <algorithm>
#include <limits>
#include <cctype>
#include <random>
#include <chrono>
#include <stdlib.h>
#include <fstream>
#include <sstream>
#include <cstdlib>
#include <cstdio>
#include <limits>
#include <stdexcept>
using std::string;
using std::cout;
using std::cin;
using std::endl;
using std::left;
using std::right;
using std::setw;
using std::vector;
using std::fixed;
using std::setprecision;
using std::mt19937;
using std::uniform_int_distribution;
using std::chrono::high_resolution_clock;
using std::sort;