if(EXISTS "D:/objektinis/v3.0/build-tests/tests/StudentuSistemaTests[1]_tests.cmake")
  include("D:/objektinis/v3.0/build-tests/tests/StudentuSistemaTests[1]_tests.cmake")
else()
  add_test(StudentuSistemaTests_NOT_BUILT StudentuSistemaTests_NOT_BUILT)
endif()
